-- ExpandServerStatus
ALTER TYPE "ServerStatus" ADD VALUE IF NOT EXISTS 'INACTIVE';
ALTER TYPE "ServerStatus" ADD VALUE IF NOT EXISTS 'MAINTENANCE';
ALTER TYPE "ServerStatus" ADD VALUE IF NOT EXISTS 'UNAVAILABLE';

-- AlterTable
ALTER TABLE "VpnServer" ADD COLUMN "flow" TEXT,
ADD COLUMN "publicKey" TEXT,
ADD COLUMN "shortId" TEXT;
